plugin:
    language:
        commands: English                            # Language you want to use for commands that matches a directory under translations.
        messages: English                            # Language you want to use for messages that matches a directory under translations.
    debugmode: false                                 # Enable/disable debugging mode and additional console output.
    usagestats: true                                 # Enable/disable usage stats reporting to CraftFire devs.
    logging: true                                    # Enable/disable logging to files.
    logformat: yyyy-MM-dd                            # Filename format of the AuthDB debug and error log files.
database:
    type: mysql                                      # Database type/driver to use. Current options are MySQL and eBean (Bukkit persistence).
    host: localhost                                  # MySQL server hostname, domain, IP, or localhost for local connections. MySQL only.
    port: 3306                                       # Port used for connecting to your MySQL server. This is usually 3306. MySQL only.
    username: root                                   # Username used to connect to your database. Only valid for MySQL.
    password: root                                   # Password used to connect to your database. MySQL only.
    name: forum                                      # Name of the database you are connecting to. MySQL only.
    keepalive: false                                 # Enable/disable keeping database connection alive. Do not use if your connection limit is low. MySQL only.
script:
    name: phpBB                                      # Name of the script you are using.
    version: 3.0.8                                   # Version of the script you are using.
    tableprefix: phpbb_                              # Database table prefix for the script, if you use one.
#    passwordsalt:                                    # NOT IMPLEMENTED YET! Unique/custom password salt, if needed by the script.
