name: AuthDB
version: ${releaseVersion}.${buildNumber}
description: Script and custom MySQL database user authentication and security plugin for Bukkit-based Minecraft servers.
authors: [CraftFire, Contex, Wulfspider]
website: http://www.authdb.com

main: com.craftfire.authdb.layer.bukkit.AuthDB
load: startup
