name: Odin
version: ${releaseVersion}.${buildNumber}
description: Script and custom MySQL database user authentication and security plugin for Bukkit-based Minecraft servers.
authors: [CraftFire, Contex, Wulfspider]
website: http://www.odin.craftfire.com

main: com.craftfire.odin.layer.bukkit.Odin
load: startup
